/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Retailer as PrismaRetailer } from "@prisma/client";

export class RetailerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.RetailerCountArgs, "select">): Promise<number> {
    return this.prisma.retailer.count(args);
  }

  async retailers(
    args: Prisma.RetailerFindManyArgs
  ): Promise<PrismaRetailer[]> {
    return this.prisma.retailer.findMany(args);
  }
  async retailer(
    args: Prisma.RetailerFindUniqueArgs
  ): Promise<PrismaRetailer | null> {
    return this.prisma.retailer.findUnique(args);
  }
  async createRetailer(
    args: Prisma.RetailerCreateArgs
  ): Promise<PrismaRetailer> {
    return this.prisma.retailer.create(args);
  }
  async updateRetailer(
    args: Prisma.RetailerUpdateArgs
  ): Promise<PrismaRetailer> {
    return this.prisma.retailer.update(args);
  }
  async deleteRetailer(
    args: Prisma.RetailerDeleteArgs
  ): Promise<PrismaRetailer> {
    return this.prisma.retailer.delete(args);
  }
  async AssignAdvertiser(args: number): Promise<boolean> {
    throw new Error("Not implemented");
  }
}
