/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Retailer } from "./Retailer";
import { RetailerCountArgs } from "./RetailerCountArgs";
import { RetailerFindManyArgs } from "./RetailerFindManyArgs";
import { RetailerFindUniqueArgs } from "./RetailerFindUniqueArgs";
import { CreateRetailerArgs } from "./CreateRetailerArgs";
import { UpdateRetailerArgs } from "./UpdateRetailerArgs";
import { DeleteRetailerArgs } from "./DeleteRetailerArgs";
import { RetailerService } from "../retailer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Retailer)
export class RetailerResolverBase {
  constructor(
    protected readonly service: RetailerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Retailer",
    action: "read",
    possession: "any",
  })
  async _retailersMeta(
    @graphql.Args() args: RetailerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Retailer])
  @nestAccessControl.UseRoles({
    resource: "Retailer",
    action: "read",
    possession: "any",
  })
  async retailers(
    @graphql.Args() args: RetailerFindManyArgs
  ): Promise<Retailer[]> {
    return this.service.retailers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Retailer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Retailer",
    action: "read",
    possession: "own",
  })
  async retailer(
    @graphql.Args() args: RetailerFindUniqueArgs
  ): Promise<Retailer | null> {
    const result = await this.service.retailer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Retailer)
  @nestAccessControl.UseRoles({
    resource: "Retailer",
    action: "create",
    possession: "any",
  })
  async createRetailer(
    @graphql.Args() args: CreateRetailerArgs
  ): Promise<Retailer> {
    return await this.service.createRetailer({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Retailer)
  @nestAccessControl.UseRoles({
    resource: "Retailer",
    action: "update",
    possession: "any",
  })
  async updateRetailer(
    @graphql.Args() args: UpdateRetailerArgs
  ): Promise<Retailer | null> {
    try {
      return await this.service.updateRetailer({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Retailer)
  @nestAccessControl.UseRoles({
    resource: "Retailer",
    action: "delete",
    possession: "any",
  })
  async deleteRetailer(
    @graphql.Args() args: DeleteRetailerArgs
  ): Promise<Retailer | null> {
    try {
      return await this.service.deleteRetailer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Query(() => Boolean)
  async AssignAdvertiser(
    @graphql.Args("args")
    args: number
  ): Promise<boolean> {
    return this.service.AssignAdvertiser(args);
  }
}
